site_name: Notas Musicais
repo_url: https://github.com/rib-thiago/notas-musicais
repo_name: rib-thiago/notas-musicais
edit_uri: /tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/python.png
  favicon: assets/python.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [notas_musicais]